### PR TITLE
Added GPT2-Wildtalk module

### PR DESCRIPTION
**Pull request by Toseban**
First version of Wildtalk using GPT2 (345M) :speaking_head: 
There are still some things to do:

- [x] Add some config options for server and gpt2-parameters :card_file_box: 
- [x] Finetuning of gpt2-parameters :gear: 
- [x] Integrate old wildtalk into server-client structure :arrow_right: Ideally plug and play for different models :electric_plug:
- [x] Currently [pytorch-pretrained-bert](https://github.com/huggingface/pytorch-pretrained-BERT) is a GitHub requirement, because the latest version on pypi does not have the 345M model yet. :construction:
- [ ] Download models when building docker image :arrow_down: 
- [ ] Add some tests! :chart:

### CODE REVIEW

**Comment by josephbirkner** [comment]
Mind Blown

**Comment by josephbirkner** [comment]
Problem: URL dependency breaks PyPI deployment. Use this handy snippet to download & install the model on first run (stolen from spacy):

**Comment by josephbirkner** [comment]
The server-client architecture with on-demand autostart is awesome. But I think we can skip integration of old Wildtalk. Nobody will use it (probably). Opinions @missxa?

**Comment by Toseban** [comment]
@josephbirkner The old Wildtalk is a more reliable in giving "normal responses" I think, so I would include it. Try the gpt2 Wildtalk for a few conversations and let me know what you think

**Comment by Toseban** [comment]
The old wildtalk module (roboy_parlai) :older_man: is now integrated as well as the conversational AI from https://github.com/huggingface/transfer-learning-conv-ai :speaking_head: 

Models and their options can be set with ravestate configs :balloon: 
Server can also be started externally on its own :earth_africa:

**Pull request merged**
